"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* @internal */
var CharacterCodes;
(function (CharacterCodes) {
    CharacterCodes[CharacterCodes["nullCharacter"] = 0] = "nullCharacter";
    CharacterCodes[CharacterCodes["maxAsciiCharacter"] = 127] = "maxAsciiCharacter";
    CharacterCodes[CharacterCodes["lineFeed"] = 10] = "lineFeed";
    CharacterCodes[CharacterCodes["carriageReturn"] = 13] = "carriageReturn";
    CharacterCodes[CharacterCodes["lineSeparator"] = 8232] = "lineSeparator";
    CharacterCodes[CharacterCodes["paragraphSeparator"] = 8233] = "paragraphSeparator";
    CharacterCodes[CharacterCodes["nextLine"] = 133] = "nextLine";
    // Unicode 3.0 space characters
    CharacterCodes[CharacterCodes["space"] = 32] = "space";
    CharacterCodes[CharacterCodes["nonBreakingSpace"] = 160] = "nonBreakingSpace";
    CharacterCodes[CharacterCodes["enQuad"] = 8192] = "enQuad";
    CharacterCodes[CharacterCodes["emQuad"] = 8193] = "emQuad";
    CharacterCodes[CharacterCodes["enSpace"] = 8194] = "enSpace";
    CharacterCodes[CharacterCodes["emSpace"] = 8195] = "emSpace";
    CharacterCodes[CharacterCodes["threePerEmSpace"] = 8196] = "threePerEmSpace";
    CharacterCodes[CharacterCodes["fourPerEmSpace"] = 8197] = "fourPerEmSpace";
    CharacterCodes[CharacterCodes["sixPerEmSpace"] = 8198] = "sixPerEmSpace";
    CharacterCodes[CharacterCodes["figureSpace"] = 8199] = "figureSpace";
    CharacterCodes[CharacterCodes["punctuationSpace"] = 8200] = "punctuationSpace";
    CharacterCodes[CharacterCodes["thinSpace"] = 8201] = "thinSpace";
    CharacterCodes[CharacterCodes["hairSpace"] = 8202] = "hairSpace";
    CharacterCodes[CharacterCodes["zeroWidthSpace"] = 8203] = "zeroWidthSpace";
    CharacterCodes[CharacterCodes["narrowNoBreakSpace"] = 8239] = "narrowNoBreakSpace";
    CharacterCodes[CharacterCodes["ideographicSpace"] = 12288] = "ideographicSpace";
    CharacterCodes[CharacterCodes["mathematicalSpace"] = 8287] = "mathematicalSpace";
    CharacterCodes[CharacterCodes["ogham"] = 5760] = "ogham";
    CharacterCodes[CharacterCodes["_"] = 95] = "_";
    CharacterCodes[CharacterCodes["$"] = 36] = "$";
    CharacterCodes[CharacterCodes["_0"] = 48] = "_0";
    CharacterCodes[CharacterCodes["_1"] = 49] = "_1";
    CharacterCodes[CharacterCodes["_2"] = 50] = "_2";
    CharacterCodes[CharacterCodes["_3"] = 51] = "_3";
    CharacterCodes[CharacterCodes["_4"] = 52] = "_4";
    CharacterCodes[CharacterCodes["_5"] = 53] = "_5";
    CharacterCodes[CharacterCodes["_6"] = 54] = "_6";
    CharacterCodes[CharacterCodes["_7"] = 55] = "_7";
    CharacterCodes[CharacterCodes["_8"] = 56] = "_8";
    CharacterCodes[CharacterCodes["_9"] = 57] = "_9";
    CharacterCodes[CharacterCodes["a"] = 97] = "a";
    CharacterCodes[CharacterCodes["b"] = 98] = "b";
    CharacterCodes[CharacterCodes["c"] = 99] = "c";
    CharacterCodes[CharacterCodes["d"] = 100] = "d";
    CharacterCodes[CharacterCodes["e"] = 101] = "e";
    CharacterCodes[CharacterCodes["f"] = 102] = "f";
    CharacterCodes[CharacterCodes["g"] = 103] = "g";
    CharacterCodes[CharacterCodes["h"] = 104] = "h";
    CharacterCodes[CharacterCodes["i"] = 105] = "i";
    CharacterCodes[CharacterCodes["j"] = 106] = "j";
    CharacterCodes[CharacterCodes["k"] = 107] = "k";
    CharacterCodes[CharacterCodes["l"] = 108] = "l";
    CharacterCodes[CharacterCodes["m"] = 109] = "m";
    CharacterCodes[CharacterCodes["n"] = 110] = "n";
    CharacterCodes[CharacterCodes["o"] = 111] = "o";
    CharacterCodes[CharacterCodes["p"] = 112] = "p";
    CharacterCodes[CharacterCodes["q"] = 113] = "q";
    CharacterCodes[CharacterCodes["r"] = 114] = "r";
    CharacterCodes[CharacterCodes["s"] = 115] = "s";
    CharacterCodes[CharacterCodes["t"] = 116] = "t";
    CharacterCodes[CharacterCodes["u"] = 117] = "u";
    CharacterCodes[CharacterCodes["v"] = 118] = "v";
    CharacterCodes[CharacterCodes["w"] = 119] = "w";
    CharacterCodes[CharacterCodes["x"] = 120] = "x";
    CharacterCodes[CharacterCodes["y"] = 121] = "y";
    CharacterCodes[CharacterCodes["z"] = 122] = "z";
    CharacterCodes[CharacterCodes["A"] = 65] = "A";
    CharacterCodes[CharacterCodes["B"] = 66] = "B";
    CharacterCodes[CharacterCodes["C"] = 67] = "C";
    CharacterCodes[CharacterCodes["D"] = 68] = "D";
    CharacterCodes[CharacterCodes["E"] = 69] = "E";
    CharacterCodes[CharacterCodes["F"] = 70] = "F";
    CharacterCodes[CharacterCodes["G"] = 71] = "G";
    CharacterCodes[CharacterCodes["H"] = 72] = "H";
    CharacterCodes[CharacterCodes["I"] = 73] = "I";
    CharacterCodes[CharacterCodes["J"] = 74] = "J";
    CharacterCodes[CharacterCodes["K"] = 75] = "K";
    CharacterCodes[CharacterCodes["L"] = 76] = "L";
    CharacterCodes[CharacterCodes["M"] = 77] = "M";
    CharacterCodes[CharacterCodes["N"] = 78] = "N";
    CharacterCodes[CharacterCodes["O"] = 79] = "O";
    CharacterCodes[CharacterCodes["P"] = 80] = "P";
    CharacterCodes[CharacterCodes["Q"] = 81] = "Q";
    CharacterCodes[CharacterCodes["R"] = 82] = "R";
    CharacterCodes[CharacterCodes["S"] = 83] = "S";
    CharacterCodes[CharacterCodes["T"] = 84] = "T";
    CharacterCodes[CharacterCodes["U"] = 85] = "U";
    CharacterCodes[CharacterCodes["V"] = 86] = "V";
    CharacterCodes[CharacterCodes["W"] = 87] = "W";
    CharacterCodes[CharacterCodes["X"] = 88] = "X";
    CharacterCodes[CharacterCodes["Y"] = 89] = "Y";
    CharacterCodes[CharacterCodes["Z"] = 90] = "Z";
    CharacterCodes[CharacterCodes["ampersand"] = 38] = "ampersand";
    CharacterCodes[CharacterCodes["asterisk"] = 42] = "asterisk";
    CharacterCodes[CharacterCodes["at"] = 64] = "at";
    CharacterCodes[CharacterCodes["backslash"] = 92] = "backslash";
    CharacterCodes[CharacterCodes["backtick"] = 96] = "backtick";
    CharacterCodes[CharacterCodes["bar"] = 124] = "bar";
    CharacterCodes[CharacterCodes["caret"] = 94] = "caret";
    CharacterCodes[CharacterCodes["closeBrace"] = 125] = "closeBrace";
    CharacterCodes[CharacterCodes["closeBracket"] = 93] = "closeBracket";
    CharacterCodes[CharacterCodes["closeParen"] = 41] = "closeParen";
    CharacterCodes[CharacterCodes["colon"] = 58] = "colon";
    CharacterCodes[CharacterCodes["comma"] = 44] = "comma";
    CharacterCodes[CharacterCodes["dot"] = 46] = "dot";
    CharacterCodes[CharacterCodes["doubleQuote"] = 34] = "doubleQuote";
    CharacterCodes[CharacterCodes["equals"] = 61] = "equals";
    CharacterCodes[CharacterCodes["exclamation"] = 33] = "exclamation";
    CharacterCodes[CharacterCodes["greaterThan"] = 62] = "greaterThan";
    CharacterCodes[CharacterCodes["hash"] = 35] = "hash";
    CharacterCodes[CharacterCodes["lessThan"] = 60] = "lessThan";
    CharacterCodes[CharacterCodes["minus"] = 45] = "minus";
    CharacterCodes[CharacterCodes["openBrace"] = 123] = "openBrace";
    CharacterCodes[CharacterCodes["openBracket"] = 91] = "openBracket";
    CharacterCodes[CharacterCodes["openParen"] = 40] = "openParen";
    CharacterCodes[CharacterCodes["percent"] = 37] = "percent";
    CharacterCodes[CharacterCodes["plus"] = 43] = "plus";
    CharacterCodes[CharacterCodes["question"] = 63] = "question";
    CharacterCodes[CharacterCodes["semicolon"] = 59] = "semicolon";
    CharacterCodes[CharacterCodes["singleQuote"] = 39] = "singleQuote";
    CharacterCodes[CharacterCodes["slash"] = 47] = "slash";
    CharacterCodes[CharacterCodes["tilde"] = 126] = "tilde";
    CharacterCodes[CharacterCodes["backspace"] = 8] = "backspace";
    CharacterCodes[CharacterCodes["formFeed"] = 12] = "formFeed";
    CharacterCodes[CharacterCodes["byteOrderMark"] = 65279] = "byteOrderMark";
    CharacterCodes[CharacterCodes["tab"] = 9] = "tab";
    CharacterCodes[CharacterCodes["verticalTab"] = 11] = "verticalTab";
})(CharacterCodes = exports.CharacterCodes || (exports.CharacterCodes = {}));
var SyntaxKind;
(function (SyntaxKind) {
    SyntaxKind[SyntaxKind["Unknown"] = 0] = "Unknown";
    // Literals
    SyntaxKind[SyntaxKind["NumericLiteral"] = 1] = "NumericLiteral";
    SyntaxKind[SyntaxKind["StringLiteral"] = 2] = "StringLiteral";
    // Punctuation
    SyntaxKind[SyntaxKind["OpenBraceToken"] = 3] = "OpenBraceToken";
    SyntaxKind[SyntaxKind["CloseBraceToken"] = 4] = "CloseBraceToken";
    SyntaxKind[SyntaxKind["OpenParenToken"] = 5] = "OpenParenToken";
    SyntaxKind[SyntaxKind["CloseParenToken"] = 6] = "CloseParenToken";
    SyntaxKind[SyntaxKind["OpenBracketToken"] = 7] = "OpenBracketToken";
    SyntaxKind[SyntaxKind["CloseBracketToken"] = 8] = "CloseBracketToken";
    SyntaxKind[SyntaxKind["DotToken"] = 9] = "DotToken";
    SyntaxKind[SyntaxKind["SemicolonToken"] = 10] = "SemicolonToken";
    SyntaxKind[SyntaxKind["CommaToken"] = 11] = "CommaToken";
    // Comparison
    SyntaxKind[SyntaxKind["LessThanToken"] = 12] = "LessThanToken";
    SyntaxKind[SyntaxKind["GreaterThanToken"] = 13] = "GreaterThanToken";
    SyntaxKind[SyntaxKind["LessThanEqualsToken"] = 14] = "LessThanEqualsToken";
    SyntaxKind[SyntaxKind["GreaterThanEqualsToken"] = 15] = "GreaterThanEqualsToken";
    SyntaxKind[SyntaxKind["EqualsEqualsToken"] = 16] = "EqualsEqualsToken";
    SyntaxKind[SyntaxKind["ExclamationEqualsToken"] = 17] = "ExclamationEqualsToken";
    SyntaxKind[SyntaxKind["EqualsGreaterThanToken"] = 18] = "EqualsGreaterThanToken";
    SyntaxKind[SyntaxKind["PlusToken"] = 19] = "PlusToken";
    SyntaxKind[SyntaxKind["MinusToken"] = 20] = "MinusToken";
    SyntaxKind[SyntaxKind["AsteriskToken"] = 21] = "AsteriskToken";
    SyntaxKind[SyntaxKind["SlashToken"] = 22] = "SlashToken";
    SyntaxKind[SyntaxKind["PercentToken"] = 23] = "PercentToken";
    SyntaxKind[SyntaxKind["PlusPlusToken"] = 24] = "PlusPlusToken";
    SyntaxKind[SyntaxKind["MinusMinusToken"] = 25] = "MinusMinusToken";
    SyntaxKind[SyntaxKind["LessThanLessThanToken"] = 26] = "LessThanLessThanToken";
    SyntaxKind[SyntaxKind["GreaterThanGreaterThanToken"] = 27] = "GreaterThanGreaterThanToken";
    SyntaxKind[SyntaxKind["AmpersandToken"] = 28] = "AmpersandToken";
    SyntaxKind[SyntaxKind["BarToken"] = 29] = "BarToken";
    SyntaxKind[SyntaxKind["CaretToken"] = 30] = "CaretToken";
    SyntaxKind[SyntaxKind["ExclamationToken"] = 31] = "ExclamationToken";
    SyntaxKind[SyntaxKind["TildeToken"] = 32] = "TildeToken";
    SyntaxKind[SyntaxKind["AmpersandAmpersandToken"] = 33] = "AmpersandAmpersandToken";
    SyntaxKind[SyntaxKind["BarBarToken"] = 34] = "BarBarToken";
    SyntaxKind[SyntaxKind["QuestionToken"] = 35] = "QuestionToken";
    SyntaxKind[SyntaxKind["ColonToken"] = 36] = "ColonToken";
    SyntaxKind[SyntaxKind["AtToken"] = 37] = "AtToken";
    // Assignments
    SyntaxKind[SyntaxKind["EqualsToken"] = 38] = "EqualsToken";
    SyntaxKind[SyntaxKind["PlusEqualsToken"] = 39] = "PlusEqualsToken";
    SyntaxKind[SyntaxKind["MinusEqualsToken"] = 40] = "MinusEqualsToken";
    SyntaxKind[SyntaxKind["AsteriskEqualsToken"] = 41] = "AsteriskEqualsToken";
    SyntaxKind[SyntaxKind["SlashEqualsToken"] = 42] = "SlashEqualsToken";
    SyntaxKind[SyntaxKind["PercentEqualsToken"] = 43] = "PercentEqualsToken";
    SyntaxKind[SyntaxKind["LessThanLessThanEqualsToken"] = 44] = "LessThanLessThanEqualsToken";
    SyntaxKind[SyntaxKind["GreaterThanGreaterThanEqualsToken"] = 45] = "GreaterThanGreaterThanEqualsToken";
    SyntaxKind[SyntaxKind["AmpersandEqualsToken"] = 46] = "AmpersandEqualsToken";
    SyntaxKind[SyntaxKind["BarEqualsToken"] = 47] = "BarEqualsToken";
    SyntaxKind[SyntaxKind["CaretEqualsToken"] = 48] = "CaretEqualsToken";
    // Reserved words
    SyntaxKind[SyntaxKind["IncludeKeyword"] = 49] = "IncludeKeyword";
    SyntaxKind[SyntaxKind["StructKeyword"] = 50] = "StructKeyword";
    SyntaxKind[SyntaxKind["StaticKeyword"] = 51] = "StaticKeyword";
    SyntaxKind[SyntaxKind["ConstKeyword"] = 52] = "ConstKeyword";
    SyntaxKind[SyntaxKind["NativeKeyword"] = 53] = "NativeKeyword";
    SyntaxKind[SyntaxKind["BreakKeyword"] = 54] = "BreakKeyword";
    SyntaxKind[SyntaxKind["ContinueKeyword"] = 55] = "ContinueKeyword";
    SyntaxKind[SyntaxKind["ReturnKeyword"] = 56] = "ReturnKeyword";
    SyntaxKind[SyntaxKind["DoKeyword"] = 57] = "DoKeyword";
    SyntaxKind[SyntaxKind["ForKeyword"] = 58] = "ForKeyword";
    SyntaxKind[SyntaxKind["WhileKeyword"] = 59] = "WhileKeyword";
    SyntaxKind[SyntaxKind["IfKeyword"] = 60] = "IfKeyword";
    SyntaxKind[SyntaxKind["ElseKeyword"] = 61] = "ElseKeyword";
    SyntaxKind[SyntaxKind["TrueKeyword"] = 62] = "TrueKeyword";
    SyntaxKind[SyntaxKind["FalseKeyword"] = 63] = "FalseKeyword";
    SyntaxKind[SyntaxKind["NullKeyword"] = 64] = "NullKeyword";
    SyntaxKind[SyntaxKind["TypedefKeyword"] = 65] = "TypedefKeyword";
    // Basic types
    SyntaxKind[SyntaxKind["BoolKeyword"] = 66] = "BoolKeyword";
    SyntaxKind[SyntaxKind["ByteKeyword"] = 67] = "ByteKeyword";
    SyntaxKind[SyntaxKind["CharKeyword"] = 68] = "CharKeyword";
    SyntaxKind[SyntaxKind["IntKeyword"] = 69] = "IntKeyword";
    SyntaxKind[SyntaxKind["FixedKeyword"] = 70] = "FixedKeyword";
    SyntaxKind[SyntaxKind["StringKeyword"] = 71] = "StringKeyword";
    // Native complex types
    SyntaxKind[SyntaxKind["AbilcmdKeyword"] = 72] = "AbilcmdKeyword";
    SyntaxKind[SyntaxKind["ActorKeyword"] = 73] = "ActorKeyword";
    SyntaxKind[SyntaxKind["ActorscopeKeyword"] = 74] = "ActorscopeKeyword";
    SyntaxKind[SyntaxKind["AifilterKeyword"] = 75] = "AifilterKeyword";
    SyntaxKind[SyntaxKind["BankKeyword"] = 76] = "BankKeyword";
    SyntaxKind[SyntaxKind["BitmaskKeyword"] = 77] = "BitmaskKeyword";
    SyntaxKind[SyntaxKind["CamerainfoKeyword"] = 78] = "CamerainfoKeyword";
    SyntaxKind[SyntaxKind["ColorKeyword"] = 79] = "ColorKeyword";
    SyntaxKind[SyntaxKind["DoodadKeyword"] = 80] = "DoodadKeyword";
    SyntaxKind[SyntaxKind["HandleKeyword"] = 81] = "HandleKeyword";
    SyntaxKind[SyntaxKind["GenerichandleKeyword"] = 82] = "GenerichandleKeyword";
    SyntaxKind[SyntaxKind["EffecthistoryKeyword"] = 83] = "EffecthistoryKeyword";
    SyntaxKind[SyntaxKind["MarkerKeyword"] = 84] = "MarkerKeyword";
    SyntaxKind[SyntaxKind["OrderKeyword"] = 85] = "OrderKeyword";
    SyntaxKind[SyntaxKind["PlayergroupKeyword"] = 86] = "PlayergroupKeyword";
    SyntaxKind[SyntaxKind["PointKeyword"] = 87] = "PointKeyword";
    SyntaxKind[SyntaxKind["RegionKeyword"] = 88] = "RegionKeyword";
    SyntaxKind[SyntaxKind["RevealerKeyword"] = 89] = "RevealerKeyword";
    SyntaxKind[SyntaxKind["SoundKeyword"] = 90] = "SoundKeyword";
    SyntaxKind[SyntaxKind["SoundlinkKeyword"] = 91] = "SoundlinkKeyword";
    SyntaxKind[SyntaxKind["TextKeyword"] = 92] = "TextKeyword";
    SyntaxKind[SyntaxKind["TimerKeyword"] = 93] = "TimerKeyword";
    SyntaxKind[SyntaxKind["TransmissionsourceKeyword"] = 94] = "TransmissionsourceKeyword";
    SyntaxKind[SyntaxKind["TriggerKeyword"] = 95] = "TriggerKeyword";
    SyntaxKind[SyntaxKind["UnitKeyword"] = 96] = "UnitKeyword";
    SyntaxKind[SyntaxKind["UnitfilterKeyword"] = 97] = "UnitfilterKeyword";
    SyntaxKind[SyntaxKind["UnitgroupKeyword"] = 98] = "UnitgroupKeyword";
    SyntaxKind[SyntaxKind["UnitrefKeyword"] = 99] = "UnitrefKeyword";
    SyntaxKind[SyntaxKind["VoidKeyword"] = 100] = "VoidKeyword";
    SyntaxKind[SyntaxKind["WaveKeyword"] = 101] = "WaveKeyword";
    SyntaxKind[SyntaxKind["WaveinfoKeyword"] = 102] = "WaveinfoKeyword";
    SyntaxKind[SyntaxKind["WavetargetKeyword"] = 103] = "WavetargetKeyword";
    // Ref types
    SyntaxKind[SyntaxKind["ArrayrefKeyword"] = 104] = "ArrayrefKeyword";
    SyntaxKind[SyntaxKind["StructrefKeyword"] = 105] = "StructrefKeyword";
    SyntaxKind[SyntaxKind["FuncrefKeyword"] = 106] = "FuncrefKeyword";
    //
    SyntaxKind[SyntaxKind["Identifier"] = 107] = "Identifier";
    SyntaxKind[SyntaxKind["EndOfFileToken"] = 108] = "EndOfFileToken";
    // Elements
    SyntaxKind[SyntaxKind["TypeReference"] = 109] = "TypeReference";
    SyntaxKind[SyntaxKind["MappedType"] = 110] = "MappedType";
    SyntaxKind[SyntaxKind["ArrayType"] = 111] = "ArrayType";
    SyntaxKind[SyntaxKind["ArrayLiteralExpression"] = 112] = "ArrayLiteralExpression";
    SyntaxKind[SyntaxKind["ElementAccessExpression"] = 113] = "ElementAccessExpression";
    SyntaxKind[SyntaxKind["PropertyAccessExpression"] = 114] = "PropertyAccessExpression";
    SyntaxKind[SyntaxKind["CallExpression"] = 115] = "CallExpression";
    SyntaxKind[SyntaxKind["PrefixUnaryExpression"] = 116] = "PrefixUnaryExpression";
    SyntaxKind[SyntaxKind["PostfixUnaryExpression"] = 117] = "PostfixUnaryExpression";
    SyntaxKind[SyntaxKind["BinaryExpression"] = 118] = "BinaryExpression";
    SyntaxKind[SyntaxKind["TypeAssertionExpression"] = 119] = "TypeAssertionExpression";
    SyntaxKind[SyntaxKind["ParenthesizedExpression"] = 120] = "ParenthesizedExpression";
    SyntaxKind[SyntaxKind["SourceFile"] = 121] = "SourceFile";
    SyntaxKind[SyntaxKind["Block"] = 122] = "Block";
    SyntaxKind[SyntaxKind["IfStatement"] = 123] = "IfStatement";
    SyntaxKind[SyntaxKind["DoStatement"] = 124] = "DoStatement";
    SyntaxKind[SyntaxKind["WhileStatement"] = 125] = "WhileStatement";
    SyntaxKind[SyntaxKind["ForStatement"] = 126] = "ForStatement";
    SyntaxKind[SyntaxKind["BreakStatement"] = 127] = "BreakStatement";
    SyntaxKind[SyntaxKind["ContinueStatement"] = 128] = "ContinueStatement";
    SyntaxKind[SyntaxKind["IncludeStatement"] = 129] = "IncludeStatement";
    SyntaxKind[SyntaxKind["ReturnStatement"] = 130] = "ReturnStatement";
    SyntaxKind[SyntaxKind["ExpressionStatement"] = 131] = "ExpressionStatement";
    SyntaxKind[SyntaxKind["EmptyStatement"] = 132] = "EmptyStatement";
    SyntaxKind[SyntaxKind["StructDeclaration"] = 133] = "StructDeclaration";
    SyntaxKind[SyntaxKind["VariableDeclaration"] = 134] = "VariableDeclaration";
    SyntaxKind[SyntaxKind["FunctionDeclaration"] = 135] = "FunctionDeclaration";
    SyntaxKind[SyntaxKind["ParameterDeclaration"] = 136] = "ParameterDeclaration";
    SyntaxKind[SyntaxKind["PropertyDeclaration"] = 137] = "PropertyDeclaration";
    SyntaxKind[SyntaxKind["TypedefDeclaration"] = 138] = "TypedefDeclaration";
})(SyntaxKind = exports.SyntaxKind || (exports.SyntaxKind = {}));
var SyntaxKindMarker;
(function (SyntaxKindMarker) {
    SyntaxKindMarker[SyntaxKindMarker["FirstToken"] = 1] = "FirstToken";
    SyntaxKindMarker[SyntaxKindMarker["LastToken"] = 107] = "LastToken";
    SyntaxKindMarker[SyntaxKindMarker["FirstKeyword"] = 49] = "FirstKeyword";
    SyntaxKindMarker[SyntaxKindMarker["LastKeyword"] = 106] = "LastKeyword";
    SyntaxKindMarker[SyntaxKindMarker["FirstBasicType"] = 66] = "FirstBasicType";
    SyntaxKindMarker[SyntaxKindMarker["LastBasicType"] = 71] = "LastBasicType";
    SyntaxKindMarker[SyntaxKindMarker["FirstComplexType"] = 72] = "FirstComplexType";
    SyntaxKindMarker[SyntaxKindMarker["LastComplexType"] = 103] = "LastComplexType";
    SyntaxKindMarker[SyntaxKindMarker["FirstTypeNode"] = 109] = "FirstTypeNode";
    SyntaxKindMarker[SyntaxKindMarker["LastTypeNode"] = 111] = "LastTypeNode";
})(SyntaxKindMarker = exports.SyntaxKindMarker || (exports.SyntaxKindMarker = {}));
;
var SymbolFlags;
(function (SymbolFlags) {
    SymbolFlags[SymbolFlags["None"] = 0] = "None";
    SymbolFlags[SymbolFlags["LocalVariable"] = 2] = "LocalVariable";
    SymbolFlags[SymbolFlags["FunctionParameter"] = 4] = "FunctionParameter";
    SymbolFlags[SymbolFlags["GlobalVariable"] = 8] = "GlobalVariable";
    SymbolFlags[SymbolFlags["Property"] = 16] = "Property";
    SymbolFlags[SymbolFlags["Function"] = 32] = "Function";
    SymbolFlags[SymbolFlags["Struct"] = 64] = "Struct";
    SymbolFlags[SymbolFlags["Typedef"] = 128] = "Typedef";
    SymbolFlags[SymbolFlags["Variable"] = 14] = "Variable";
    SymbolFlags[SymbolFlags["FunctionScopedVariable"] = 6] = "FunctionScopedVariable";
})(SymbolFlags = exports.SymbolFlags || (exports.SymbolFlags = {}));
var TypeFlags;
(function (TypeFlags) {
    TypeFlags[TypeFlags["Unknown"] = 1] = "Unknown";
    TypeFlags[TypeFlags["String"] = 2] = "String";
    TypeFlags[TypeFlags["Integer"] = 4] = "Integer";
    TypeFlags[TypeFlags["Byte"] = 8] = "Byte";
    TypeFlags[TypeFlags["Char"] = 16] = "Char";
    TypeFlags[TypeFlags["Fixed"] = 32] = "Fixed";
    TypeFlags[TypeFlags["Boolean"] = 64] = "Boolean";
    TypeFlags[TypeFlags["Nullable"] = 128] = "Nullable";
    TypeFlags[TypeFlags["StringLiteral"] = 256] = "StringLiteral";
    TypeFlags[TypeFlags["NumericLiteral"] = 512] = "NumericLiteral";
    TypeFlags[TypeFlags["BooleanLiteral"] = 1024] = "BooleanLiteral";
    TypeFlags[TypeFlags["Void"] = 2048] = "Void";
    TypeFlags[TypeFlags["Null"] = 4096] = "Null";
    TypeFlags[TypeFlags["Struct"] = 8192] = "Struct";
    TypeFlags[TypeFlags["Function"] = 16384] = "Function";
    TypeFlags[TypeFlags["Complex"] = 32768] = "Complex";
    TypeFlags[TypeFlags["Array"] = 65536] = "Array";
    TypeFlags[TypeFlags["Mapped"] = 131072] = "Mapped";
    TypeFlags[TypeFlags["Reference"] = 262144] = "Reference";
    TypeFlags[TypeFlags["Typedef"] = 2097152] = "Typedef";
    TypeFlags[TypeFlags["True"] = 4194304] = "True";
    TypeFlags[TypeFlags["False"] = 8388608] = "False";
    /* @internal */
    TypeFlags[TypeFlags["Literal"] = 1792] = "Literal";
    TypeFlags[TypeFlags["Numeric"] = 36] = "Numeric";
})(TypeFlags = exports.TypeFlags || (exports.TypeFlags = {}));
var NodeCheckFlags;
(function (NodeCheckFlags) {
    NodeCheckFlags[NodeCheckFlags["TypeChecked"] = 1] = "TypeChecked";
    NodeCheckFlags[NodeCheckFlags["ContextChecked"] = 2] = "ContextChecked";
})(NodeCheckFlags = exports.NodeCheckFlags || (exports.NodeCheckFlags = {}));
//
// Diagnostics
//
var DiagnosticCategory;
(function (DiagnosticCategory) {
    DiagnosticCategory[DiagnosticCategory["Warning"] = 0] = "Warning";
    DiagnosticCategory[DiagnosticCategory["Error"] = 1] = "Error";
    DiagnosticCategory[DiagnosticCategory["Message"] = 2] = "Message";
})(DiagnosticCategory = exports.DiagnosticCategory || (exports.DiagnosticCategory = {}));
//# sourceMappingURL=types.js.map